#!/bin/bash
# PortKnocking Client - Used to open SSH port's on remote host
# Diego Neves <diego@diegoneves.eti.br>
# 2016-04-20
# https://github.com/diegoaceneves/firewall
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <phk@FreeBSD.ORG> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Poul-Henning Kamp
# ----------------------------------------------------------------------------


#Ports used on knocking
PORTS=(1000 2000 3000 4000)


if [ -b $1 ]; then
	echo "use {$0 host}"
	exit 
fi

for i in "${PORTS[@]}"; do
	wget $1:$i --connect-timeout=1 -t 1 > /dev/null 2> /dev/null
	echo sending: $1:$i
done

#It's recommended to configure user in $HOME/.ssh/config 
	ssh $1
